# Generated by Django 5.2 on 2025-05-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_certificate_contact_education_experience_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(default='', upload_to='certificates/pdfs/'),
            preserve_default=False,
        ),
    ]
