# Generated by Django 5.2 on 2025-05-18 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_certificate_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='certificate_image',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='certificate_image',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='certificate_image',
        ),
    ]
